In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])
print(x)
print(y)

[1 2 3 4]
[5 6 7 8]


In [3]:
print(x + y)
print(np.add(x, y))

[ 6  8 10 12]
[ 6  8 10 12]


In [5]:
print(x - y)
print(np.subtract(x, y))

[-4 -4 -4 -4]
[-4 -4 -4 -4]


In [6]:
print(x * y)
print(np.multiply(x, y))

[ 5 12 21 32]
[ 5 12 21 32]


In [7]:
print(x / y)
print(np.divide(x, y))

[0.2        0.33333333 0.42857143 0.5       ]
[0.2        0.33333333 0.42857143 0.5       ]


In [13]:
x = np.array([1, 2, 3, 4]).reshape(2, 2)
print('x')
print(x)

print()

y = np.array([4, 5, 6, 7]).reshape(2, 2)
print('y')
print(y)

x
[[1 2]
 [3 4]]

y
[[4 5]
 [6 7]]


In [14]:
print(x + y)

[[ 5  7]
 [ 9 11]]


In [11]:
print(x - y)

[[-3 -3]
 [-3 -3]]


In [17]:
print(x / y)

[[0.25       0.4       ]
 [0.5        0.57142857]]


In [16]:
print(x * y)

[[ 4 10]
 [18 28]]


In [18]:
x = np.array([1, 2, 3, 4])
print(x)

[1 2 3 4]


In [19]:
print(np.sqrt(x))

[1.         1.41421356 1.73205081 2.        ]


In [22]:
print(np.exp(x))

[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [23]:
print(np.power(x, 2))

[ 1  4  9 16]


In [24]:
x = np.array([1, 2, 3, 4]).reshape(2, 2)
print(x)

[[1 2]
 [3 4]]


In [26]:
print("avg", x.mean())
print("avg of columns", x.mean(axis=0))
print("avg of rows", x.mean(axis=1))

avg 2.5
avg of columns [2. 3.]
avg of rows [1.5 3.5]


In [27]:
print("sum", x.sum())
print("sum of columns", x.sum(axis=0))
print("sum of rows", x.sum(axis=1))

sum 10
sum of columns [4 6]
sum of rows [3 7]


In [28]:
x.std()

1.118033988749895

In [29]:
np.median(x)

2.5

In [30]:
x.max()

4

In [31]:
x.min()

1

In [32]:
print(x)

[[1 2]
 [3 4]]


In [33]:
print(x + 3)

[[4 5]
 [6 7]]


In [34]:
print(x - 3)

[[-2 -1]
 [ 0  1]]


In [35]:
print(x * 2)

[[2 4]
 [6 8]]


In [36]:
print(x / 2)

[[0.5 1. ]
 [1.5 2. ]]


In [37]:
y = np.arange(9).reshape(3, 3)
print("y:")
print(y)

print()

x = np.arange(3)
print("x:")
print(x)

y:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

x:
[0 1 2]


In [38]:
print(y + x)

[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]]


In [39]:
z = np.arange(3).reshape(3,1)
print("z:")
print(z)

z:
[[0]
 [1]
 [2]]


In [40]:
print(y + z)

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]
