In [1]:
import numpy as np

In [2]:
x = np.arange(25).reshape(5, 5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [4]:
print(x[x > 10])

[11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [5]:
print(x[x < 7])

[0 1 2 3 4 5 6]


In [7]:
print(x[(x > 5 )& (x < 10)])

[6 7 8 9]


In [8]:
y = np.copy(x)
y[(y > 9) & (y < 16)] = -1
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [-1 -1 -1 -1 -1]
 [-1 16 17 18 19]
 [20 21 22 23 24]]


In [10]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([3, 6, 7, 8, 1])

print(np.intersect1d(x, y))
print(np.setdiff1d(x, y))
print(np.union1d(x, y))

[1 3]
[2 4 5]
[1 2 3 4 5 6 7 8]


In [12]:
x = np.random.randint(1, 21, size=(10,))
print(x)

[ 4 11 15  6 16 20 14 16 12 11]


In [13]:
print(np.sort(x))

[ 4  6 11 11 12 14 15 16 16 20]


In [14]:
print(np.sort(np.unique(x)))

[ 4  6 11 12 14 15 16 20]


In [15]:
x = np.random.randint(1, 21, size=(10,))
print(x)

x.sort()
print(x)

[ 5  9 15  9 17 14  6 19  8 11]
[ 5  6  8  9  9 11 14 15 17 19]


In [16]:
x = np.random.randint(1, 21, size=(5, 5))
print(x)

[[ 9 15  4  5  5]
 [12  3 12 17  7]
 [ 6 17  5 13 10]
 [14 10  6  6  6]
 [18  6 14 12 11]]


In [17]:
print(np.sort(x, axis=0))

[[ 6  3  4  5  5]
 [ 9  6  5  6  6]
 [12 10  6 12  7]
 [14 15 12 13 10]
 [18 17 14 17 11]]


In [18]:
print(np.sort(x, axis=1))

[[ 4  5  5  9 15]
 [ 3  7 12 12 17]
 [ 5  6 10 13 17]
 [ 6  6  6 10 14]
 [ 6 11 12 14 18]]
