In [2]:
import numpy as np

In [3]:
x = np.array([1, 2, 3, 4, 5])
print(x)

[1 2 3 4 5]


In [6]:
print("1st element:", x[0])
print("2st element:", x[1])
print("last element:", x[-1])
print("4th element:", x[-2])

1st element: 1
2st element: 2
last element: 5
4th element: 4


In [7]:
x[3] = 20
print(x)

[ 1  2  3 20  5]


In [8]:
x = np.arange(1, 10).reshape(3, 3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
x[1,1]= 0
print(x)

[[1 2 3]
 [4 0 6]
 [7 8 9]]


In [10]:
x = np.array([1, 2, 3, 4, 5])
print(x)

x = np.delete(x, [0, 4])
print(x)

[1 2 3 4 5]
[2 3 4]


In [16]:
x = np.arange(1, 10).reshape(3, 3)
print(x)

y = np.delete(x, 0, axis=1) # axis 1 = column 0 will be deleted
print(y)

y  = np.delete(x, 0, axis=0) # axis 0 = row 0  will be deleted
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]
[[4 5 6]
 [7 8 9]]


In [18]:
x = np.array([1, 2, 3, 4, 5])
print(x)

x = np.append(x, [6, 7, 8, 9, 10])
print(x)

[1 2 3 4 5]
[ 1  2  3  4  5  6  7  8  9 10]


In [25]:
x = np.arange(1, 10).reshape(3, 3)
print(x)

y = np.append(x, [[10, 11, 12]], axis=0) # axios 0 = will append a new row
print(y)

y = np.append(x, [[10], [11], [12]], axis=1) # axios 0 = will append a new column
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


In [29]:
x = np.array([1, 2, 6, 7, 8, 9, 10])
print(x)

x = np.insert(x, 2, [3, 4, 5])
print(x)

[ 1  2  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [43]:
x = np.array([[1, 2, 3], [7, 8, 9]])
print(x)

[[1 2 3]
 [7 8 9]]


In [48]:
y = np.insert(x, 1, [4, 5, 6], axis=0) # axis 0 = will add a new row between before row 1 (7, 8, 9)
print(y)

y = np.insert(x, 1, 0, axis=1) # axis 1 = will add a new column with value 0 in each row, before element 1
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 0 2 3]
 [7 0 8 9]]


In [57]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('x:', x)
y = np.array([10, 11, 12])
print('y:', y)

x: [[1 2 3]
 [4 5 6]
 [7 8 9]]
y: [10 11 12]


In [58]:
z = np.vstack((x, y))
print(z)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [59]:
z = np.hstack((x, y.reshape(3, 1)))
print(z)

[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]
