In [1]:
import numpy as np

x = np.array([1, 2, 3, 4, 5])

In [2]:
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
x.dtype

dtype('int64')

In [4]:
x.shape

(5,)

In [5]:
y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [6]:
y.shape

(4, 3)

In [7]:
y.size

12

In [8]:
x = np.array(['Hello', 'World'])
print(x)

['Hello' 'World']


In [9]:
print('shape:', x.shape)
print('type:', type(x))
print('dtype', x.dtype)

shape: (2,)
type: <class 'numpy.ndarray'>
dtype <U5


In [10]:
x = np.array([1, 2, 'Hello World'])
print(x)
print('shape:', x.shape)
print('type:', type(x))
print('dtype', x.dtype)

['1' '2' 'Hello World']
shape: (3,)
type: <class 'numpy.ndarray'>
dtype <U21


In [11]:
x = np.array([1, 2.5, 3])
print(x)
print('shape:', x.shape)
print('type:', type(x))
print('dtype', x.dtype)

[1.  2.5 3. ]
shape: (3,)
type: <class 'numpy.ndarray'>
dtype float64


In [12]:
x = np.array([1.5, 2.2, 3.7], dtype=np.int64)
print(x)
print('shape:', x.shape)
print('type:', type(x))
print('dtype', x.dtype)

[1 2 3]
shape: (3,)
type: <class 'numpy.ndarray'>
dtype int64


In [13]:
x = np.array([1, 2, 3, 4, 5])
np.save('numpy_intro_array', x)

In [14]:
y = np.load('numpy_intro_array.npy')
print(y)

[1 2 3 4 5]
