In [1]:
import numpy as np

my_list = [1, 2, 3, 4, 5]
np.array(my_list)

array([1, 2, 3, 4, 5])

In [9]:
x = np.zeros((3, 4))
y = np.zeros((2, 3), dtype=int)
print('x', x)
print('x dtype', x.dtype)
print('y:', y)
print('y dtype:', y.dtype)

x [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
x dtype float64
y: [[0 0 0]
 [0 0 0]]
y dtype: int64


In [13]:
x = np.full((3, 3), 1)
y = np.full((3, 3), 1, dtype=np.float64)
print('x', x)
print('x dtype', x.dtype)
print('y', y)
print('y dtype', y.dtype)

x [[1 1 1]
 [1 1 1]
 [1 1 1]]
x dtype int64
y [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
y dtype float64


In [14]:
x = np.diag([10, 20, 30, 40, 50])
print(x)

[[10  0  0  0  0]
 [ 0 20  0  0  0]
 [ 0  0 30  0  0]
 [ 0  0  0 40  0]
 [ 0  0  0  0 50]]


In [16]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [18]:
x = np.arange(5, 15)
print(x)

[ 5  6  7  8  9 10 11 12 13 14]


In [21]:
x = np.arange(1, 22, 2)
print(x)

[ 1  3  5  7  9 11 13 15 17 19 21]


In [25]:
x = np.linspace(0, 30, 6)
print(x)

[ 0.  6. 12. 18. 24. 30.]


In [26]:
 x = np.linspace(0, 30, 6, endpoint=False)
print(x)

[ 0.  5. 10. 15. 20. 25.]


In [28]:
x = np.reshape(x, (2, 3))
print(x)

[[ 0.  5. 10.]
 [15. 20. 25.]]


In [29]:
x = np.arange(50).reshape((5, 10))
print(x)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]


In [35]:
x = np.linspace(0, 60, 12, endpoint=False).reshape((4, 3))
print(x)

[[ 0.  5. 10.]
 [15. 20. 25.]
 [30. 35. 40.]
 [45. 50. 55.]]


In [36]:
x = np.random.random((5, 5))
print(x)

[[0.44953884 0.27658381 0.44515054 0.88267258 0.45189528]
 [0.39121394 0.39734341 0.76360075 0.79268497 0.77341492]
 [0.6195701  0.61280902 0.39697013 0.79811532 0.72957967]
 [0.83905686 0.74232315 0.03375339 0.67407502 0.88664582]
 [0.42380308 0.24667073 0.13928859 0.07627419 0.77329363]]


In [37]:
x = np.random.randint(1, 10, (3, 3))
print(x)

[[7 4 7]
 [9 7 9]
 [1 2 1]]


In [38]:
x = np.random.normal(0, 0.1, size=(10,10))
print(x)

[[-0.14024017 -0.01486017 -0.09901123  0.18943106  0.15971242 -0.11192121
   0.11282301 -0.0005547   0.02355374 -0.04570871]
 [ 0.14699274 -0.02577624  0.08217451 -0.03878073  0.10243444 -0.05592412
  -0.18666087  0.02452253  0.01455335 -0.08860745]
 [ 0.01769897  0.22415921  0.01107956 -0.00101289  0.05449106 -0.0363518
   0.04956133 -0.13077962 -0.0165008   0.04908879]
 [ 0.09342185  0.08180432  0.03607972 -0.09619947  0.15157216  0.06497469
   0.12298305 -0.02561909 -0.14791352  0.08480624]
 [ 0.043237    0.07772362  0.05107362  0.11503602 -0.29543737  0.0408529
   0.03186446 -0.11520649 -0.12863726  0.07689922]
 [ 0.08117085 -0.02850392 -0.09564587 -0.01731365  0.04588973 -0.0494701
  -0.01371855  0.0191142  -0.00484268 -0.00250431]
 [-0.13793995 -0.12751087 -0.00791733 -0.11653484  0.14637045 -0.16922976
   0.11176447 -0.11652711  0.04568123  0.04916013]
 [ 0.02744101 -0.09408118 -0.09948578  0.12968426 -0.09531792  0.00198215
  -0.03902804 -0.18434626  0.06507946 -0.01909952]
 [ 

In [39]:
print('mean:', x.mean())
print('standard deviation:', x.std())
print('max', x.max())
print('min:', x.min())
print('# positive', (x > 0).sum())
print('# negative', (x < 0).sum())

mean: -0.0026310767201801082
standard deviation: 0.09258372389252803
max 0.224159210990298
min: -0.2954373688947658
# positive 48
# negative 52
