In [1]:
import numpy as np

1. ndarray[start:end]

2. ndarray[start:]

3. ndarray[:end]

In [2]:
x = np.arange(1, 21).reshape(4, 5)
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [4]:
y = x[1:, 2:]
print(y)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [5]:
y = x[:3, 2:]
print(y)

[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]]


In [8]:
y = x[:, 3:]
print(y)

[[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]]


In [9]:
y = x[:, 3]
print(y)

[ 4  9 14 19]


In [16]:
x = np.arange(1, 21).reshape(4, 5)
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [17]:
y = x[2:, 3:5]
print(y)

[[14 15]
 [19 20]]


In [18]:
y[0][0] = 999
y[1][1] = 999
print(y)
print(x)

[[999  15]
 [ 19 999]]
[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13 999  15]
 [ 16  17  18  19 999]]


In [20]:
x = np.arange(1, 26).reshape(5, 5)
print(x)
y = np.copy(x)
y[0][0] = 0
y[1][1] = 0
y[2][2] = 0
y[3][3] = 0
y[4][4] = 0
print(y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 0  2  3  4  5]
 [ 6  0  8  9 10]
 [11 12  0 14 15]
 [16 17 18  0 20]
 [21 22 23 24  0]]


In [21]:
indices = np.array([1, 3])
print(indices)

[1 3]


In [23]:
x = np.arange(1, 26).reshape(5, 5)
y = x[indices, :]
print(y)
z = x[:, indices]
print(z)

[[ 6  7  8  9 10]
 [16 17 18 19 20]]
[[ 2  4]
 [ 7  9]
 [12 14]
 [17 19]
 [22 24]]


In [26]:
x = np.arange(1, 26).reshape(5, 5)
print(x)
y = np.diag(x)
print(y)
y = np.diag(x, k=1)
print(y)
y = np.diag(x, k=-1)
print(y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[ 1  7 13 19 25]
[ 2  8 14 20]
[ 6 12 18 24]


In [28]:
x = np.array([[1, 2, 3], [4, 3, 2], [5, 1, 3], [6, 4, 2]])
print(x)
y = np.unique(x)
print(y)

[[1 2 3]
 [4 3 2]
 [5 1 3]
 [6 4 2]]
[1 2 3 4 5 6]
